CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255)        NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS limits
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limit_sum                DECIMAL(15, 2)           NOT NULL,
    limit_datetime           TIMESTAMP WITH TIME ZONE NOT NULL,
    limit_currency_shortname VARCHAR(3)               NOT NULL,
    category                 VARCHAR(50),
    user_id                  BIGINT                   NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS transactions
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_from       BIGINT                   NOT NULL,
    account_to         BIGINT                   NOT NULL,
    currency_shortname VARCHAR(3)               NOT NULL,
    sum                DECIMAL(15, 2)           NOT NULL,
    expense_category   VARCHAR(255),
    datetime           TIMESTAMP WITH TIME ZONE NOT NULL,
    limit_exceeded     BOOLEAN DEFAULT FALSE,
    limit_id           BIGINT,
    FOREIGN KEY (account_from) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (account_to) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (limit_id) REFERENCES limits (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS exchange_rates
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_pair VARCHAR(7)     NOT NULL,
    rate          DECIMAL(15, 6) NOT NULL,
    updated_at    TIMESTAMP      NOT NULL
);