CREATE TABLE IF NOT EXISTS exchange_rates
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_pair VARCHAR(7)     NOT NULL,
    rate          DECIMAL(15, 6) NOT NULL,
    date          DATE           NOT NULL
);
